### DISCUSSION TITLE
Trouble with webviews after set up with terraform

### DISCUSSION THREAD

**Discussion by AttaboySawyer** [eclipse-theia/theia-cloud#171] [Q&A]
Hello,

I have set up theia cloud using the terraform configurations for minikube, and am trying to get my theia application running, but the webviews are not working in the cloud. This is the error I am getting in the sidebar:
 
![image](https://user-images.githubusercontent.com/83662258/236035756-2dcbae46-e041-4163-8af4-5770e882f762.png)

After looking into discussions of others that ran into a similar issue, I think I have narrowed down the problem to ingress not recognizing the *.webview prefix in the URL, or something along those lines, as the webviews run perfectly fine in a local docker container. Following other discussions, I have changed the instance-ingress.yaml to include the webview specific URL:
```
spec:
  tls:
    - hosts:
        {{- if .Values.hosts.usePaths }}
        - {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
        - "*.webview.{{ tpl (.Values.hosts.paths.baseHost | toString) . }}"
        {{- else }}
        - {{ tpl (.Values.hosts.instance | toString) . }}
        - "*.webview.{{ tpl (.Values.hosts.instance | toString) . }}"
          secretName: ws-cert-secret
        {{- end }}
  rules:
    {{- if .Values.hosts.usePaths }}
    - host: {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
      http:
    - host: "*.webview.{{ tpl (.Values.hosts.paths.baseHost | toString) . }}"
      http:
    {{- else }}
    - host: {{ tpl (.Values.hosts.instance | toString) . }}
      http:
    - host: "*.webview.{{ tpl (.Values.hosts.instance | toString) . }}"
      http:
    {{- end }}
```

However, I am still getting the same error. 

Is there a different way to get webviews running in theia cloud using terraform? Or are there other errors I might be missing in this approach?
