### DISCUSSION TITLE
Multiple Theia Versions on the Theia Cloud Landing page

### DISCUSSION THREAD

**Discussion by Mtze** [eclipse-theia/theia-cloud#301] [Q&A]
Hi again :) 

I'm trying to get multiple theia ide version working in my theia cloud deplyoment. There is an option to define multiple images in `AppDefinition` and link them in the landing page. 

My helm config looks like this: 

````
...
landingPageo:
  appDefinition: ""
  additionalApps:
    theia-go: 
      label: Theia Go
```
Unfortunately the landing page never shows a dropdown - it just forwards to the demo app no matter what is configured in addition. 

Any ideas what I configured wrong? Thanks in advance

**Comment by lucas-koehler** [comment]
Hi @Mtze ,
I see a typo in your pasted snippet. It says `landingPageo` instead of `landingPage`.
Assuming you don't have this typo in your values, you might still not see the dropdown because you use the landing page instead of the try now page. There are two different pages that can be used.

The default page directly forwards the user to their session without any dropdown or the need to click a button to launch the session.
There is another page (the so-called try now page) that offers this drop down. The try now page is used by theia cloud's try now deployment at https://try.theia-cloud.io/.

The 'Try Now' page can be found in the repo here: https://github.com/eclipsesource/theia-cloud/tree/main/node/try-now-page

There is a plan to unify these pages. The resulting page will be more like the try now page.

For now, you can try using the published try now page image instead of the landing page: https://hub.docker.com/r/theiacloud/theia-cloud-try-now-page . To achieve this, adapt the `landingPage.image` in the helm values for the theia cloud chart:

```yaml
landingPage:
  # -- the landing page image to use
  image: theiacloud/theia-cloud-try-now-page:0.10.0
```
