### DISCUSSION TITLE
Failed to execute 'replace' on 'Location'; 'https://' is not a valid URL

### DISCUSSION THREAD

**Discussion by wss29** [eclipse-theia/theia-cloud#409] [Q&A] [answered]
hi,
   Has anyone encountered this kind of problem before? 
![image](https://github.com/user-attachments/assets/46996c2c-6801-40ac-832f-368320072be2)

  the application image runs fine on Kubernetes using the following nginx.yaml, but when I set it up on Theia Cloud, the error mentioned above appears.
```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginxweb
spec:
    selector:
        matchLabels:
            app: nginxweb1
    replicas: 2
    template:
        metadata:
            labels:
                app: nginxweb1
        spec:
            containers:
                - name: nginxwebc
                  image: kiada:0.1
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
    name: nginxweb-service
spec:
    externalTrafficPolicy: Cluster
    type: LoadBalancer
    selector:
        app: nginxweb1
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
```
