### ISSUE TITLE
Improve ingress patching

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia-cloud#365]
### Is your feature request related to a problem? Please describe.

Currently the instances-ingress gets created/upgraded when running helm install/upgrade, but also gets patched by the operator if there are new appdefinitions or sessions.

This currently leads to quite some problems:
On helm upgrade we set the hosts to the same values we had before the upgrade, this will result in changed values not being applied (e.g. allWildcardInstances)
When upgrading a separate appDefinition helm chart added appDefinitions will not be updated in the ingress, hence they wont work.

This makes the upgrade process harder or even impossible. We should investigate on how we can improve this.

### Describe the solution you'd like

One solution might be to handle the ingress completely by the operator.

### Describe alternatives you've considered

-

**Comment by jfaltermeier** [comment]
I think we should move the upgrading AppDefinitions topic to a separate ticket.

We haven't really defined what should happen at runtime if an AppDefinition changes.
Currently, no updates are applied to running sessions, so only new sessions will use the updated definition.
For more significant changes, it would probably make sense to publish a new AppDefinition anyway and remove the deprecated one later, once no users are relying on it anymore.

At the moment, this can be managed by users.

**Comment by jfaltermeier** [comment]
I think we can identify the rules that are not bound to a session by checking whether `http.paths` is configured.

We add these empty rules for two reasons:

- to ensure the Ingress remains valid even when no sessions exist
- to allow certificate creation and renewal even when no sessions exist

So we can probably check if `http` or `http.paths` is empty to detect such cases.

Examples:

```
# Empty:
  rules:
    - host: ws.192.168.59.211.nip.io
    - host: '*.foo.ws.192.168.59.211.nip.io'
    - host: '*.bar.ws.192.168.59.211.nip.io'

# Session Subdomains:
  rules:
    - host: ws.192.168.59.211.nip.io
    - host: '*.foo.ws.192.168.59.211.nip.io'
    - host: '*.bar.ws.192.168.59.211.nip.io'
    - host: ws.192.168.59.211.nip.io
      http:
        paths:
          - path: /e7516447-0008-4994-95fa-b270fd0344f1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: session-foo-theia-cloud-demo-b270fd0344f1
                port:
                  number: 3000
    - host: '*.foo.ws.192.168.59.211.nip.io'
      http:
        paths:
          - path: /e7516447-0008-4994-95fa-b270fd0344f1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: session-foo-theia-cloud-demo-b270fd0344f1
                port:
                  number: 3000

# Session Paths
 rules:
    - host: 192.168.59.211.nip.io
    - host: '*.foo.192.168.59.211.nip.io'
    - host: '*.foobar.192.168.59.211.nip.io'
    - host: 192.168.59.211.nip.io
      http:
        paths:
          - path: /instances/58917945-fafb-4d79-9a1f-0faf38014062(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: session-foo-theia-cloud-demo-0faf38014062
                port:
                  number: 3000
    - host: '*.foo.192.168.59.211.nip.io'
      http:
        paths:
          - path: /instances/58917945-fafb-4d79-9a1f-0faf38014062(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: session-foo-theia-cloud-demo-0faf38014062
                port:
                  number: 3000
```
